from msr_etl.adapters.base import DataAdapter
from msr_etl.adapters.exampleIndividialAdapter import ExampleIndividualAdapter
from msr_etl.adapters.ubr_adapter import UBRIndividualAdapter, UBRLocationAdapter
