# Generated by Django 4.2.30 on 2026-08-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msr_etl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MsrEtlSyncUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_uuid', models.UUIDField(db_index=True)),
                ('unit_type', models.CharField(choices=[('DISTRICT', 'District'), ('TA', 'TA'), ('GVH', 'GVH'), ('VILLAGE', 'Village'), ('PERCENTILE_CHUNK', 'Percentile chunk')], max_length=32)),
                ('unit_code', models.CharField(max_length=64)),
                ('stage_status', models.CharField(choices=[('PENDING', 'Pending'), ('STAGED', 'Staged'), ('SYNCED', 'Synced'), ('FAILED', 'Failed')], default='PENDING', max_length=16)),
                ('sync_status', models.CharField(choices=[('PENDING', 'Pending'), ('STAGED', 'Staged'), ('SYNCED', 'Synced'), ('FAILED', 'Failed')], default='PENDING', max_length=16)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('record_count', models.IntegerField(blank=True, null=True)),
                ('record_identities', models.JSONField(blank=True, null=True)),
                ('error_detail', models.TextField(blank=True, null=True)),
                ('attempts', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'msr_etl_sync_unit',
            },
        ),
        migrations.DeleteModel(
            name='UBRLocationInitialPullStatus',
        ),
        migrations.AddIndex(
            model_name='msretlsyncunit',
            index=models.Index(fields=['job_uuid', 'sync_status'], name='msr_etl_syn_job_uui_762c22_idx'),
        ),
    ]
