# Generated by Django 4.2.30 on 2026-09-25 11:43

from django.db import migrations, models


def backfill_kind(apps, schema_editor):
    # Existing rows are all UBR; only percentile chunks are individual units.
    MsrEtlSyncUnit = apps.get_model("msr_etl", "MsrEtlSyncUnit")
    MsrEtlSyncUnit.objects.exclude(unit_type="PERCENTILE_CHUNK").update(kind="location")


class Migration(migrations.Migration):

    dependencies = [
        ('msr_etl', '0002_msretlsyncunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='msretlsyncunit',
            name='kind',
            field=models.CharField(choices=[('individual', 'Individual'), ('location', 'Location')], default='individual', max_length=16),
        ),
        migrations.AddField(
            model_name='msretlsyncunit',
            name='source_type',
            field=models.CharField(default='ubr', max_length=64),
        ),
        migrations.RunPython(backfill_kind, migrations.RunPython.noop),
    ]
